data:
  vocalset:
    root: /ext/projects/disentangle/datasets/vocalset
    seed: 42
    ratio: .9
  sample_rate: &sample_rate 16000

  mel_spec:
    sample_rate: *sample_rate
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: &n_mels 64

  attrs: &attrs [
    singer, 
    context,
    technique,
    vowel]

  loader:
    batch_size: 2
    shuffle: false
    drop_last: false
    num_workers: 1
    pin_memory: true

model:
  encoder:
    attrs: *attrs
    d_input: *n_mels
    d_model: 32
    d_latent: 2
    n_heads: 8
    n_layers: 2
    max_duration: 1024
    rates: [0, 0, 0, 0]

    #     d_input: 64
    # d_latent: 2
    # n_head: 8
    # num_layers_encoder: 1
    # d_feedforward_encoder: 256
    # num_layers_decoder: 1
    # d_feedforward_decoder: 256
    # dist: 'ContinuousBernoulli'
    # swap: True
    # rnd_rates: False
